### ISSUE TITLE
auto click box

### ISSUE THREAD

**Issue by Chanoski926** [Onewaysidewalks/col-reforger#3]
![reforger error](https://user-images.githubusercontent.com/75600173/101959142-9b92a680-3bb9-11eb-8579-7f9c360423a0.png)

The mouse would auto click in the red area

**Comment by Onewaysidewalks** [comment]
great feed back, ill release a version that makes this configurable, based on % of the window. If you want to tune where it clicks, you can set the dimensions in the included `yaml` file like so:

```
execution:
  maxAttempts: 300 # How many reforges max to do
  widthRatioForClick: .8 #what percentage from the left of the window the click should occurr
  heightRatioForClick: .9 #what percentage from the top of the window the click should occur
```

Note the number is likely between `.7` and `.9`. Based on your screen shot, id go with the new defaults and see how it works out. You likely only need to adjust the `widthRatioForClick`
